# Generated by Django 2.1.8 on 2019-10-16 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=32)),
                ('article_description', models.TextField()),
                ('article_content', models.TextField()),
                ('article_pub_time', models.DateField()),
                ('article_image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=32)),
                ('type_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=32)),
                ('author_age', models.IntegerField()),
                ('author_birthday', models.DateField()),
                ('author_gender', models.CharField(max_length=32)),
                ('author_email', models.EmailField(max_length=254)),
                ('author_phone', models.CharField(max_length=32)),
                ('author_photo', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='article_author',
            field=models.ManyToManyField(to='article.Author'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType'),
        ),
    ]
