# Generated by Django 2.1.8 on 2019-10-22 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_number', models.CharField(max_length=32)),
                ('good_name', models.CharField(max_length=32)),
                ('goods_description', models.TextField()),
                ('goods_price', models.FloatField()),
                ('goods_content', models.IntegerField()),
                ('goods_pub_time', models.DateField(auto_now=True)),
                ('goods_shelf_life', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_label', models.CharField(max_length=32)),
                ('type_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('user_phone', models.CharField(max_length=32)),
                ('user_image', models.ImageField(default='seller/images/1.png', upload_to='seller/images')),
                ('user_address', models.TextField()),
                ('user_type', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.GoodsType'),
        ),
    ]
